
GET http://localhost:8080/calibre HTTP/1.1
###
GET http://localhost:8080/calibre/63c6e41dc4a935a8d141c7e6 HTTP/1.1
###
GET http://localhost:8080/calibre/63c6e41dc4a935a8d141c7e7 HTTP/1.1
###
GET http://localhost:8080/calibre/63c6e41dc4a935a8d141c7e8 HTTP/1.1
###
POST http://localhost:8080/calibre HTTP/1.1
Content-Type: application/json

{
    "cartridgeName": "308 Win",
    "calibre": "308",
    "bulletWeight": "150",
    "muzzleVelocity": "2980",
    "bulletEnergyAtMuzzle": "2957.2",
    "bulletMomentumAtMuzzle": "63.9",
    "bulletSectionalDensity": "0.226",
    "recoilEnergy": "16.60"
}
###


PUT http://localhost:8080/calibre/63c6f16dc93504ce96831e48 HTTP/1.1
Content-Type: application/json

{
    "cartridgeName": "308Win",
    "calibre": "308",
    "bulletWeight": "150",
    "muzzleVelocity": "2980",
    "bulletEnergyAtMuzzle": "2957.2",
    "bulletMomentumAtMuzzle": "63.9",
    "bulletSectionalDensity": "0.226",
    "recoilEnergy": "16.60"
}
###
DELETE http://localhost:8080/calibre/




###
//production
GET https://huntershelp.onrender.com/calibre HTTP/1.1
###
GET https://huntershelp.onrender.com/calibre/63c6e41dc4a935a8d141c7e6 HTTP/1.1
###
GET https://huntershelp.onrender.com/calibre/63c6e41dc4a935a8d141c7e7 HTTP/1.1
###
GET https://huntershelp.onrender.com/calibre/63c6e41dc4a935a8d141c7e8 HTTP/1.1
###
