//Localhost Rest
GET http://localhost:8080/calibre HTTP/1.1
Content-Type: application/json

{"age": 18}

###
GET http://localhost:8080/calibre/63c71366c4a935a8d141c7ec HTTP/1.1
Content-Type: application/json

{"age": 18}

###
GET http://localhost:8080/calibre/63c71366c4a935a8d141c7ed HTTP/1.1
Content-Type: application/json

{"age": 18}
###
GET http://localhost:8080/calibre/63c8bc6bbf037546fbc45909 HTTP/1.1
Content-Type: application/json

{"age": 18}
###
POST http://localhost:8080/calibre HTTP/1.1
Content-Type: application/json

{
    "cartridgeName": "222222 Long Rifle",
    "calibre": ".224",
    "bulletWeight": "26",
    "muzzleVelocity": "1650",
    "bulletEnergyAtMuzzle": "157.1",
    "bulletMomentumAtMuzzle": "6.1",
    "bulletSectionalDensity": "0.074",
    "recoilEnergy": "0.10",
    "game": "Small Game(short and medium range)",
    "age": 18
    
}
###

PUT http://localhost:8080/calibre/63c71366c4a935a8d141c7ec HTTP/1.1
Content-Type: application/json

{

    "cartridgeName": "6.5551 Creedmore",
    "calibre": ".264",
    "bulletWeight": "140",
    "muzzleVelocity": "2710",
    "bulletEnergyAtMuzzle": "2282.5",
    "bulletMomentumAtMuzzle": "54.2",
    "bulletSectionalDensity": "0.287",
    "recoilEnergy": "12.94",
    "age": 18
  }
###
DELETE http://localhost:8080/calibre/63cc5d87798a4fa6a94f8c13
Content-Type: application/json

{"age": 18}





###

###
//User information... on localhost.
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "userName": "Jermery Wheeler",
    "userEmail": "jermery@mail.com",
    "userAge": 47
}

###
GET http://localhost:8080/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/users/63d48c881ceb278a65241756 HTTP/1.1
Content-Type: application/json
###
PUT http://localhost:8080/users/63d48c881ceb278a65241756 HTTP/1.1
Content-Type: application/json

{
    "userName": "Anna E. Wheeler",
    "userEmail": "anna@mail.com",
    "userAge": 35
}
###
DELETE http://localhost:8080/users/63d48b951ceb278a65241755 HTTP/1.1
Content-Type: application/json
###





//production Rest
GET https://huntershelp.onrender.com/calibre HTTP/1.1
Content-Type: application/json

{"age": 18}
###
GET https://huntershelp.onrender.com/calibre/63c71366c4a935a8d141c7ec HTTP/1.1
Content-Type: application/json

{"age": 18}
###
GET https://huntershelp.onrender.com/calibre/63c71366c4a935a8d141c7ed HTTP/1.1
Content-Type: application/json

{"age": 18}
###
GET https://huntershelp.onrender.com/calibre/63c717524147be778e962ef4 HTTP/1.1
Content-Type: application/json

{"age": 18}
###
POST https://huntershelp.onrender.com/calibre HTTP/1.1
Content-Type: application/json

{
    "cartridgeName": "8x57 Mauser",
    "calibre": ".323",
    "bulletWeight": "198",
    "muzzleVelocity": "2460",
    "bulletEnergyAtMuzzle": "2666.0",
    "bulletMomentumAtMuzzle": "69.6",
    "bulletSectionalDensity": "0.271",
    "recoilEnergy": "12.68",
    "age":18
}
###
PUT https://huntershelp.onrender.com/calibre/63ccd5a931af4e6e2306973a HTTP/1.1
Content-Type: application/json


    {
    "cartridgeName": "Hello",
    "calibre": ".323",
    "bulletWeight": "198",
    "muzzleVelocity": "2460.6",
    "bulletEnergyAtMuzzle": "2666.0",
    "bulletMomentumAtMuzzle": "69.6",
    "bulletSectionalDensity": "0.271",
    "recoilEnergy": "12.68",
    "age": 18
}

###
DELETE https://huntershelp.onrender.com/calibre/63ccd66131af4e6e2306973b HTTP/1.1
Content-Type: application/json

{"age": 18}

###